config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :events do
    resources :requests, only: :create
  end
  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:new, :create]
  end

  resources :requests, only: :destroy
  get "accounts/show", to: "accounts#show", as: "dashboard"
  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
  resources :users, only: [:index, :show] do
    resources :notifications, only: :index, as: "notifications"
  end
  get '/search', to: 'application#search'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-expand-sm footer-light footer-lewagon">
   <p>© 2023 TravelTribe</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-nav">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "TT_Logo.png" %>
        <p id="logoname">Travel<br>Tribe</p>
      <% end %>

      <div id="navbarSupportedContent">
          <% if user_signed_in? %>
              <%= link_to "Tribe", users_path, class: "nav-link" %>
              <%= link_to "Events", events_path, class: "nav-link" %>
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu", style: "object-fit: cover", id: "navbarDropdown" %>
              <% else %>
                <%= image_tag "default_avatar.jpg", class: "avatar", alt: "dropdown menu", style: "object-fit: cover", id: "navbarDropdown" %>
              <% end %>

              <% if current_user.notifications.where(read: false).present? %>
                <i class="fa-solid fa-circle notification-dot" style="color: #EE9C22;"></i>
              <% end %>

            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My Dashboard", dashboard_path, class: "dropdown-item" %>
                <%= link_to "Create Event", new_event_path, class: "dropdown-item" %>
                <%= link_to "Notifications", user_notifications_path(current_user), class: "dropdown-item" %>
                <%= link_to "Chats", chatrooms_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, id: "navbar-button" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
      </div>
    </div>
  </div>
</div>