config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :events do
    resources :requests, only: :create
  end
  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:new, :create]
  end

  resources :requests, only: :destroy
  get "accounts/show", to: "accounts#show", as: "dashboard"
  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
  resources :users, only: [:index, :show] do
    resources :notifications, only: :index, as: "notifications"
  end
  get '/search', to: 'application#search'
end

app/models/event.rb
class Event < ApplicationRecord
  after_create :create_chatroom
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_one :chatroom, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  has_many :notifications, :as => :notifiable, dependent: :destroy
  validates :title, :description, :location, :capacity, :start_date, :end_date, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def attendees
    User.joins(:requests).where(requests: { event: self, status: "accepted" })
  end

  def attendees_including_creator
    users = attendees + User.joins(:events).where(events: {id: id } )
    User.where(id: users.pluck(:id))
  end

  def is_full?
    self.attendees.count >= self.capacity
  end

  private

  def create_chatroom
    Chatroom.create(event: self)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    @event = Event.new
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR location ILIKE :query"
      @events = Event.where(sql_subquery, query: "%#{params[:query]}%")
    end

    @no_results = @events.empty?

    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {event: event})
      }
    end
  end

  def show
    @attendees = @event.attendees
    @chatroom = @event.chatroom
    @marker = [{
      lat: @event.latitude,
      lng: @event.longitude
    }]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @attendees = @event.attendees.to_a
    @event.destroy
    @attendees.each do |attendee|
      Notification.create(
        content: "The event #{@event.title} has been cancelled by #{@event.user.username}",
        user: attendee,
        notifiable_type: attendee.class.name,
        notifiable_id: attendee.id
      )
    end
    redirect_to root_path, alert: "Event was successfully deleted."
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :start_date, :end_date, :capacity, :photo)
  end
end

app/views/events/_events_map.html.erb
<div class="map"
  data-controller="events-map"
  data-action="showMap@window->events-map#resize"
  data-events-map-markers-value="<%= @markers.to_json %>"
  data-events-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<br>

app/views/events/_form.html.erb
<div class="form-container">
    <%= simple_form_for(event) do |f| %>
      <%= f.input :location %>
      <%= f.input :start_date, as: :string,
                input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :end_date, as: :string,
                input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :title %>
      <%= f.input :capacity %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file, input_html: { required:false }%>
      <%= f.submit class:"btn" %>
    <% end %>
</div>

app/views/events/_info_window.html.erb
  <h2><%= link_to event.title, event_path(event) %></h2>
  <p><i class="fa-sharp fa-solid fa-location-dot" style="color: #0b7176;"></i> <%= event.location %></p>

<% if event.photo.key %>
  <%= cl_image_tag event.photo.key, crop: :fill, class:"popup-image" %>
<% end %>

app/views/events/_map.html.erb
<div class="map"
  data-controller="map"
  data-map-markers-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/events/edit.html.erb
<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="container" data-controller="toggle">
  <%= form_with(url: events_path, method: "get", local: true, class: "search-form-control form-group") do |form| %>
    <%= form.text_field :query, class: "form-control string required", id: "search_query", placeholder: "Search Event by name/location" %>
    <%= form.button type: "submit", class: "btn btn-flat" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>

  <div  class="mt-5">
    <div class="toggle-map" data-action="click->toggle#fire">
      <i class="fa-solid fa-map-location-dot" style="color: #0b7176;"></i>
      <p data-toggle-target="text"></p>
    </div>
    <div data-toggle-target="togglableElement" class="d-none">
      <%= render "events_map", events: @event %>
    </div>
  </div>

  <div class="cards" data-toggle-target="cardsMap">
    <% if @no_results %>
      <p>No results found.</p>
    <% else %>
      <% @events.each do |event|%>
        <a href="<%= event_path(event) %>">
          <div class="card-grid">
            <% if event.photo.key %>
              <%= cl_image_tag event.photo.key, crop: :fill, class:"events-image" %>
            <% else %>
              <%= image_tag "TT_Logo.png" %>
            <% end %>
            <div class="event-descriptions">
              <div class="description-column">
                <div class="row">
                  <h2 class="title"><%= event.title %></h2>
                      <% if event.start_date != event.end_date %>
                        <h2 class="listing"><%= event.start_date %> to <%= event.end_date %></h2>
                      <% else %>
                        <h2 class="listing"><%= event.start_date %></h2>
                      <% end %>
                  <h2 class="listing">
                    <i class="fa-sharp fa-solid fa-location-dot" style="color: #ffffff;"></i>
                    <%= event.location %>
                  </h2>
                  <div class="icon-right">
                    <h2 class="listing">
                      <i class="fa-solid fa-user" style="color: #ffffff;"></i>
                      <%= event.capacity %>
                    </h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <br>
        </a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<br>
<div><%= render "form", event: @event %></div>

app/views/events/show.html.erb
<div class="container">
  <div class="card-show">
    <div class="card-grid">
      <% if @event.photo.key %>
        <%= cl_image_tag @event.photo.key %>
      <% end %>
      <div class="event-descriptions">
        <div class="description-column">
          <div class="row">
            <h2 class="title"> <%= @event.title %></h2>
            <h2 class="listing"><%= @event.description %></h2>
            <h2 class="listing"><%= @event.start_date %> to <%= @event.end_date %></h2>
            <h2 class="listing"> <i class="fa-sharp fa-solid fa-location-dot" style="color: #ffffff;"></i> <%= @event.location %></h2>
            <div class="icon-right"><h2 class="listing"> <i class="fa-solid fa-user" style="color: #ffffff;"></i> <%= @event.capacity %></h2></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <h2 class="avatar-text">
    <%= link_to image_tag(url_for(@event.user.photo), id: "avatar-small"), user_path(@event.user), style: "object-fit: cover" %>
    <%= @event.user.username %> posted this event
  </h2>
</div>

<div class="container-join-event">
  <% if Request.find_by(event:@event, user:current_user, status: "accepted") %>
    <%= button_to "Leave Event", request_path(Request.find_by(event: @event, user:current_user)), method: :delete, class: "button" %>
  <% elsif Request.find_by(event:@event, user:current_user, status: "pending") %>
    <span>Your request is pending.</span>
  <% elsif Request.find_by(event:@event, user:current_user, status: "rejected") %>
    <span>Your request has been rejected.</span>
  <% elsif @event.attendees.count < @event.capacity && current_user != @event.user %>
    <%= button_to "Join Event" , event_requests_path(@event), class: "button" %>
  <% elsif @event.attendees.count >= @event.capacity && current_user != @event.user %>
    <span>The event is now full.</span>
  <% end %>

  <div class="chat-button-container">
    <% if @event.user == current_user %>
      <%= button_to edit_event_path(@event), method: :get, class: "button" do %>
        <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i> Edit
      <% end %>
    <% end %>

    <% if @event.user == current_user %>
      <%= link_to event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" }, class: "button" do %>
        <i class="fa-sharp fa-regular fa-circle-xmark" style="color: #ffffff;"></i> Delete
      <% end %>
    <% end %>
  </div>
</div>

<br>

<div class="container">
  <div class="map">
    <%= render "map" %>
  </div>
</div>

<div class="container-join-event">
  <div class="event-links">
    <div class="chat-button-container">
      <% if @attendees.include?(current_user) || @event.user == current_user %>
        <%= button_to "Event Chat", chatroom_path(@chatroom, template: "chatrooms/show"), method: :get, class: "button" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <p>Attendees:</p>
  <div class="avatar-container">
    <% @attendees.each do |attendee| %>
      <%= link_to image_tag(url_for(attendee.photo), class: "avatar-attendee"), user_path(attendee), style: "object-fit: cover" %>
    <% end %>
  </div>
</div>

<br>

app/views/events/show.htmls.erb
<h2><%= @event.title %></h2>
<h2><%= @event.description %></h2>
<h2><%= @event.location %></h2>
<h2><%= @event.start_date %></h2>
<h2><%= @event.end_date %></h2>
<h2><%= @event.capacity %></h2>