config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :events do
    resources :requests, only: :create
  end
  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:new, :create]
  end

  resources :requests, only: :destroy
  get "accounts/show", to: "accounts#show", as: "dashboard"
  patch "/requests/:id/accept", to: "requests#accept", as: "accept"
  patch "/requests/:id/reject", to: "requests#reject", as: "reject"
  resources :users, only: [:index, :show] do
    resources :notifications, only: :index, as: "notifications"
  end
  get '/search', to: 'application#search'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show
    @created_events = @user.events.order(created_at: :desc)
    @sent_requests = @user.requests.order(created_at: :desc)
    @received_requests = Request.where(event_id: @created_events.pluck(:id), status: "pending")

    @attending_events = Event.where(id: @sent_requests.pluck(:event_id).uniq)
  end

  private

  def set_user
    @user = current_user
  end
end

app/views/accounts/show.html.erb
<div class="container">
  <div class="card-show">
    <div class="attending-section">
      <div class="account-event-titles">
        <h4>Attending</h4>
        <h6>View Past Events</h6>
      </div>
      <% @attending_events.each do |event| %>
        <% if event.start_date >= Date.today && event.requests.exists?(status: "accepted") %>
          <div class="attending-accepted"><%= link_to event.title, event_url(event), class:"links-white" %></div>
        <% end %>
        <% if event.start_date >= Date.today && event.requests.exists?(status: "pending") %>
          <div class="attending-pending">
            <%= link_to event.title, event_url(event), class:"links-white" %>
            <h6><em>Pending</em></h6>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="hosting-section">
      <div class="account-event-titles">
        <h4>Hosting</h4>
        <h6>View Past Events</h6>
      </div>
       <% @created_events.each do |event| %>
        <div class="hosting-events" data-controller="toggle">
          <div class="hosting-events-title <%= "hosting-events-title-col" if @received_requests.where(event_id: event).empty? %>">
            <%= link_to event.title, event_url(event), class:"links-white" %>
            <% if @received_requests.where(event_id: event).present? %>
              <h6 data-action="click->toggle#display">Manage Requests <i class="fa-solid fa-circle-chevron-down"></i></h6>
            <% else %>
              <span id="no-requests">You don't have any pending requests.</span>
            <% end %>
          </div>
          <div class="d-none" data-toggle-target="togglableElement" >
            <% if @received_requests.present? %>
              <% @received_requests.where(event_id: event).each do |request| %>
              <div class="hosting-events-request">
                <%= request.user.username %> has requested to join the event.
                <%= link_to accept_path(request), data: { turbo_method: :patch } do %>
                  <i class="fa-sharp fa-regular fa-circle-check" style="color: #00bd16;"></i>
                <% end %>
                <%= link_to reject_path(request), data: { turbo_method: :patch } do %>
                  <i class="fa-sharp fa-regular fa-circle-xmark" style="color: #f50000;"></i>
                <% end %>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="card-show">
    <div class="card-grid">
      <% if @user.photo.key %>
        <%= cl_image_tag @user.photo.key %>
      <% end %>
      <div class="event-descriptions">
        <div class="description-column">
          <div class="row">
            <h2 class="title"> <%= @user.username %></h2>
            <h2 class="listing"> <%= @user.age %> years old</h2>
            <h2 class="listing"> <%= @user.description %></h2>
            <div class="icon-right">
              <h2 class="listing">
                <i class="fa-sharp fa-solid fa-location-dot" style="color: #ffffff;"></i>
                <%= @user.location %>
              </h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= button_to edit_user_registration_path(@user), method: :get, class: "button edit-account-button" do %>
    <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i> Edit Account
  <% end %>
</div>